#!/usr/bin/bash
TAG=rpatronilo-thesis

OLD_IMAGE=$(docker images -q $TAG)
if [ -z $OLD_IMAGE ]; then
    echo No old image
fi

docker build -t $TAG . && \
NEW_IMAGE=$(docker images -q $TAG)
echo Image successfully built with tag $TAG and id $NEW_IMAGE && \
([[ -z $OLD_IMAGE &&  $OLD_IMAGE != $NEW_IMAGE ]] || (docker rmi -f $OLD_IMAGE; echo Old image $OLD_IMAGE deleted))
