#!/usr/bin/bash
IMAGE=rpatronilo-thesis
CONTAINER_NAME=$IMAGE

SHM_SIZE=1G

ARGS=(--gpus all --name $CONTAINER_NAME --shm-size=$SHM_SIZE)



if docker ps -a --filter "name=$CONTAINER_NAME"; then
    echo Attempting to remove old container...
    docker rm $CONTAINER_NAME
fi

HOST_DIR=${HOST_DIR:-$(pwd)}
CONTAINER_DIR=/workspace/
MOUNTS=(logs data storage debug)

for dir in ${MOUNTS[@]}; do
    ARGS+=(-v $HOST_DIR$dir:$CONTAINER_DIR$dir)
done

if [ -f .env ]; then
    ARGS+=(--env-file .env)
fi

for arg in $@; do
    if [[ $arg == "IMG" ]]; then
        ARGS+=($IMAGE)
    elif [[ $arg == "-d" ]]; then
        ARGS+=($arg)
        DETACHED=true
    else
        ARGS+=($arg)
    fi
done

CMD="docker run ${ARGS[@]}"

echo Running command: 
echo
echo $CMD
echo
eval $CMD

if [[ $DETACHED == true ]]; then
    echo
    echo Container running in detached mode
    echo
    echo To stop the container, run:
    echo docker stop $CONTAINER_NAME
    echo
    echo "Attaching to logs... (you can detach with Ctrl+C)"
    docker logs -f $CONTAINER_NAME
fi


